### ISSUE TITLE
sparse matrices production

### ISSUE THREAD

**Issue by Martin-Jia** [intel/daal#163]
**Description**
I'm developing an algorithm with daal and found that when calling the SpBlas::xxcsrmm function, it discards each NaN value in the C matrix. 

There's a small demo that can reproduce this case.
![image](https://user-images.githubusercontent.com/54347731/67355996-65483100-f58b-11e9-8c6a-06a6dd98c567.png)

Before calling the xxcsrmm function, the 4th value of matrix C is NaN, and beta is 0. The formula of xxcsrmm is C = alpha * AB + beta * C. Normally, any operation with NaN will return an NaN, so after the production, the 4th value of matrix C is also expected to be an NaN, while I got the output be be 319619. 
![image](https://user-images.githubusercontent.com/54347731/67361281-b90e4680-f59a-11e9-999a-61ab405c39f8.png)

**To Reproduce**
1. Prepare a matrix C which contains some NaN values and set beta to be 0.
2. Call Spblas::xxcsrmm.
3. The output C loses the expected NaN values.

**Expected behavior**
For the demo above, the 4th value of matrix C should be NaN but not a meaningful value after the xxcsrmm operation.

**Environment:**
 - OS: Red Hat Linux Server release 7.6
 - Compiler: gcc (GCC) 8.3.0
 - Version: v2020

**Comment by SmirnovEgorRu** [comment]
Hi @Martin-Jia , as I know it is not exactly C = alpha * AB + beta * C
For case beta == 0 it should have separate branch of code which do: C = alpha * AB. It is reasonable, because C is result and memory for this can be just allocated, but not initialized - so, from time to time you will have NaN/Inf in this just allocated memory what will lead to non-deterministic and not expected results. Also, it reduces amount of FLOPS for computation.

**Comment by Martin-Jia** [comment]
> Hi @Martin-Jia , as I know it is not exactly C = alpha * AB + beta * C
> For case beta == 0 it should have separate branch of code which do: C = alpha * AB. It is reasonable, because C is result and memory for this can be just allocated, but not initialized - so, from time to time you will have NaN/Inf in this just allocated memory what will lead to non-deterministic and not expected results. Also, it reduces amount of FLOPS for computation.

If there are any other accelerations when beta or alpha equals to other value?

**Comment by SmirnovEgorRu** [comment]
@Martin-Jia, I think it is possible to reduce amount of FLOPS in case alpha/beta == 0 or 1 only. In other cases it should be C = alpha * AB + beta * C explicitly.

**Comment by Martin-Jia** [comment]
@SmirnovEgorRu Thank you.
