### ISSUE TITLE
DAAL 2020 Spark kmeans crash

### ISSUE THREAD

**Issue by MacChen01** [intel/daal#174]
Using DAAL 2020 in Spark kmeans has crash problem. The error log :

   A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f30b7cb86cf, pid=21839, tid=0x00007f30c68f4700

  JRE version: OpenJDK Runtime Environment (8.0_161-b16) (build 1.8.0_161-internal-Cloud_Programming_framework_TD_V100R001C00B223-b16)
 Java VM: OpenJDK 64-Bit Server VM (25.161-b16 mixed mode linux-amd64 )
 Problematic frame:
 C  [**libJavaAPI.so**+0x22396cf]  daal::services::interface1::Status daal::JavaNumericTable<10010>::**getTBlock<double>**(unsigned long, unsigned long, daal::data_management::ReadWriteMode, daal::data_management::interface1::BlockDescriptor<double>&, char const*, char const*)+0x12f

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

An error report file with more information is saved as:
 /data/sdj/nm-local-dir/usercache/root/appcache/application_1572491123048_0003/container_1572491123048_0003_01_000027/hs_err_pid21839.log
[thread 139846865626880 also had an error]

**Environment info：**
  OS : CentOS Linux release 7.6.1810
  DAAL: 2020
  HADOOP: 2.7.6
  Spark：2.3.0
  JDK: 1.8.0
   HiBench: 7.0

**Test procedure：**
  1. Install and config hadoop/spark/daal.
  2. Test kmeans using hibench shell and cmd :
    source /opt/intel/daal/bin/daalvars.sh intel64   SHAREDLIBS=${DAALROOT}/lib/${daal_ia}_lin/libJavaAPI.so,${DAALROOT}/../tbb/lib/${daal_ia}_lin/gcc4.4/libtbb.so.2,${DAALROOT}/../tbb/lib/${daal_ia}_lin/gcc4.4/libtbbmalloc.so.2
echo "==============$LD_LIBRARY_PATH"
run_spark_job --jars ${DAALROOT}/lib/**daal.jar** --files ${SHAREDLIBS} com.intel.daal.sparkbench.ml.DaalKMeans -k $K --numIterations $MAX_ITERATION $INPUT_HDFS/samples

**LOG file：**

[hs_err_pid21839.log.txt](https://github.com/intel/daal/files/3792425/hs_err_pid21839.log.txt)

**Comment by MacChen01** [comment]
**Test data size:**

HiBench-HiBench-7.0/conf/workloads/ml/kmeans.conf

hibench.kmeans.custom.num_of_clusters           5
hibench.kmeans.custom.dimensions               4000
hibench.kmeans.custom.num_of_samples           4800000
hibench.kmeans.custom.samples_per_inputfile    12000
hibench.kmeans.custom.max_iteration            10
hibench.kmeans.custom.k                        500
hibench.kmeans.custom.convergedist             0.5

**Comment by PivovarA** [comment]
OK. Already started to deal with this.

**Comment by PivovarA** [comment]
The first step is to make sure that everything was builded correctly. In my case, I added <code>daal.jar</code> to hibench
<code>mvn install:install-file -Dfile="<path-to-daal>/lib/daal.jar" -DgroupId=DAAL -DartifactId=DAAL -Dversion=1.0 -Dpackaging=jar</code>
and add it to dependency in POM.
```
<dependency>
   <groupId>DAAL</groupId>\
   <artifactId>DAAL</artifactId>
   <scope>system</scope>
   <version>1.0</version>
   <systemPath><path-to-daal>/lib/daal.jar</systemPath>
</dependency>
```
Next I added <code>KMeans.scala</code> from daal samples to *HiBench/sparkbench/ml/src/main/scala/com/intel/sparkbench/ml*
and replace 
<code>import org.apache.spark.mllib.clustering.KMeans </code>
to 
<code>import daal_for_mllib.{KMeans, DAALKMeansModel => KMeansModel}</code>.
If you are sure, that you buld everything in correct way, you may skip this steps.
**Be careful!** Some <code>spark.ml.clustering</code> methods are not supported by current version of DAAL.KMeans.scala (e.g. <code>setK</code> or <code>setMaxIterations</code>. Use <code>setNClusters</code> and <code>setNIterations</code> instead).

Make sure, that evironment is configured correctly:
```
export SCALA_JARS=/usr/share/scala/lib/scala-library.jar
declare -a jars=(
    "spark-core_"
    "spark-sql_"
    "spark-catalyst_"
    "spark-mllib_"
    "hadoop-common-"
    "jackson-annotations-"
    "breeze_"
    "breeze-macros_"
    "hadoop-mapreduce-client-common-"
    "hadoop-mapreduce-client-core-"
    "spark-tags_"
    "spark-unsafe_"
    "log4j-"
)

for i in "${jars[@]}"
do
    export CLASSPATH=`sudo find / -name "${i}*.jar" | head -n 1`:$CLASSPATH
done
export CLASSPATH=${SCALA_JARS}:$CLASSPATH
daal_ia="intel64"
export SHAREDLIBS=${DAALROOT}/lib/${daal_ia}_lin/libJavaAPI.so,${DAALROOT}/../tbb/lib/${daal_ia}_lin/gcc4.4/libtbb.so.2,${DAALROOT}/../tbb/lib/${daal_ia}_lin/gcc4.4/libtbbmalloc.so.2
```
Add correct settings to spark-submit. You can edit <code>run_spark_job</code> in <code>workload_functions.sh</code> to start it in correct way.
In my case <code>SUBMIT_CMD</code> looks like:
<code>${SPARK_HOME}/bin/spark-submit --driver-class-path \"${DAALROOT}/lib/daal.jar:${SCALA_JARS}\" --jars ${DAALROOT}/lib/daal.jar --files ${SHAREDLIBS} --properties-file ${SPARK_PROP_CONF} --class ${CLS} --master ${SPARK_MASTER} ${YARN_OPTS} ${SPARKBENCH_JAR} $@"</code>

**Comment by MacChen01** [comment]
@PivovarA 
**submit_cmd output is :**
Submit Spark job: /home/spark-2.3.0/bin/spark-submit --jars /opt/intel/daal/lib/daal.jar --files /opt/intel/daal/lib/intel64_lin/libJavaAPI.so,/opt/intel/daal/../tbb/lib/intel64_lin/gcc4.4/libtbb.so.2,/opt/intel/daal/../tbb/lib/intel64_lin/gcc4.4/libtbbmalloc.so.2 --properties-file /home/HiBench-HiBench-7.0/report/kmeans/spark/conf/sparkbench/spark.conf --class com.intel.daal.sparkbench.ml.DaalKMeans --master yarn-client --num-executors 5 --executor-cores 4 --executor-memory 70g --driver-java-options "" --conf "spark.executor.extraJavaOptions=" /home/HiBench-HiBench-7.0/sparkbench/assembly/target/sparkbench-assembly-7.0-dist.jar -k 500 --numIterations 10 hdfs://192.168.1.1:9000/HiBench/Kmeans/Input/samples

**Comment by MacChen01** [comment]
@PivovarA 

![daal_failed_function](https://user-images.githubusercontent.com/11262916/68188446-2206ad00-ffe4-11e9-9d27-cd25efd12f9b.png)

The crash function is getTBlock, **local_tls.jenv** pointer is normal, **but the value of pointer is error**.

![daal_error](https://user-images.githubusercontent.com/11262916/68188769-d86a9200-ffe4-11e9-9d50-c8d8266fd726.PNG)

**Comment by MacChen01** [comment]
@PivovarA 
Daal is evaluated for using in our projects， please help to solve the problem as soon as possible, thanks.

**Comment by PivovarA** [comment]
The problem may be that the size of the numeric table into which the dataset is split should not exceed 2 GB.
In this case, you can edit the sample as follows:
In GetAsPairRDD (107 line of KMeans.scala) method add
```
 val DataNCols = data.first.toArray.length
 val GBPerTable = 0.5
 val Rows = math.ceil(GBPerTable / DataNCols / 8 * 1024 * 1024 * 1024).toInt
```
and then edit 
```
val maxRows: Int = 100000
```
(111 line of KMeans.scala)
to
```
val maxRows: Int = Rows
```

**Comment by MacChen01** [comment]
@PivovarA 
**1. It didn't work. GetAsPairRDD method add:**
![daal_suggest_code](https://user-images.githubusercontent.com/11262916/68286505-2a321b80-00bc-11ea-9f84-0e44f4008b84.PNG)

**2. The max value of curRow is less than default maxRows(100000)**
![daal_error_row](https://user-images.githubusercontent.com/11262916/68290385-d840c400-00c2-11ea-99b3-5a0ca25654c9.PNG)

**3. Spark error log**
![spark_error_log](https://user-images.githubusercontent.com/11262916/68290923-c0b60b00-00c3-11ea-91c9-b4913a025c14.PNG)

**4. Jdk error log file:**
[hs_err_pid9364.log.txt](https://github.com/intel/daal/files/3813922/hs_err_pid9364.log.txt)

**Comment by PivovarA** [comment]
@MacChen01 
How many partitions do you have on this dataset ?

**Comment by MacChen01** [comment]
@PivovarA 
Did you reproduce the problem ?

**Comment by MacChen01** [comment]
The crash function is getTBlock, local_tls.jenv pointer is normal, but the value of pointer is error.
As shown below，the memmap is the value of  jenv pointer. what functions may crash the mem?

![mem_space1](https://user-images.githubusercontent.com/11262916/68446934-2c5dbc80-0219-11ea-8709-9d4b2a32c357.PNG)

**Comment by PivovarA** [comment]
It seems that the problem is that empty partitions come across.
In my case, repartition helped me.
In ```GetAsPairRDD``` (107 line of KMeans.scala) method:
```
 val DataNCols = data.first.toArray.length
 val DataNRows = data.count()
 val GBPerPartition = 0.5
 val PartitionRows = math.ceil(GBPerPartition / DataNCols / 8 * 1024 * 1024 * 1024).toInt
 val NPartitions = math.ceil(DataNRows/PartitionRows).toInt + 1

val tablesRDD = data.repartition(NPartitions).mapPartitions(
    ...
)
```
**Be careful!** Partition size should not exceed 2GB.
In addition, I recommend using the KMeans.scala code from the master branch.

**Comment by MacChen01** [comment]
**It didn't work...**, how to checking the size of partition?

![spark_error_log](https://user-images.githubusercontent.com/11262916/68586251-399bd500-04bf-11ea-8322-7f2e6ac15e67.PNG)

**Comment by PivovarA** [comment]
@MacChen01 
You can find average size of partitions using:
```
val DataNCols = data.first.toArray.length
val DataNRows = data.count()
TotalDatasetSizeGb = DataNCols * DataNRows * 8 / 1024/ 1024/ 1024
AvPartitionSizeGb = TotalDatasetSizeGb / data.partitions.size
println("average size of partition: " + AvPartitionSizeGb )
```
also, if you want to check size of each partition
```
data.foreachPartitions({
    (it: Iterator[Vector]) => {
        val arr = it.toArray
        val sizeGb  = arr.length * arr(0).toArray.length * 8 / 1024/1024/1024
        println("size of partition: "  + sizeGb)
    }
})
```

**Comment by MacChen01** [comment]
@PivovarA 
**The partition size is 366Mb**

![partitionsize](https://user-images.githubusercontent.com/11262916/68726553-c4361e80-05fc-11ea-855d-19df5d5e4646.PNG)

**Comment by PivovarA** [comment]
@MacChen01 
DAAL KMeans has been officially integrated into hibench.
The DAL module in HiBench can be built by adding `-Dmodules -Pdal`, for example:
`mvn -Psparkbench -Dmodules -Pml -Pdal -Dspark=2.0 -Dscala=2.11 clean package`
To run the workload, install DAL and setup the environment variable required by DAL. Then we can run HiBench scripts to generate the data and run it, just like other HiBench workloads.
`bin/workloads/dal/kmeans/prepare/prepare.sh`
`bin/workloads/dal/kmeans/spark/run.sh`
I tested 2 cases: 
```
hibench.kmeans.custom.num_of_clusters 5
hibench.kmeans.custom.dimensions 4000
hibench.kmeans.custom.num_of_samples 2000000
hibench.kmeans.custom.samples_per_inputfile 6000
hibench.kmeans.custom.max_iteration 10
hibench.kmeans.custom.k 500
hibench.kmeans.custom.convergedist 0.5
```
```
hibench.kmeans.custom.num_of_clusters 5
hibench.kmeans.custom.dimensions 4000
hibench.kmeans.custom.num_of_samples 4800000
hibench.kmeans.custom.samples_per_inputfile 15000
hibench.kmeans.custom.max_iteration 10
hibench.kmeans.custom.k 500
hibench.kmeans.custom.convergedist 0.5
```
All cases were successful.

Cluster Configuration: 
**AWS EMR 6 slave nodes m5.4xlarge + 1 master node m5.4xlarge**
HADOOP: 2.8.5
Spark：2.4.4

**Comment by napetrov** [comment]
I assume that this question have been answered.  @MacChen01 do you need any additional help here?
