### ISSUE TITLE
C++ examples can't be built via source code distribution

### ISSUE THREAD

**Issue by PovelikinRostislav** [intel/daal#179]
**Describe the bug**
C++ examples doesn't have appropriate makefiles. Makefiles in repository for C++ examples looks like like a stub for further deployment, e.g. all of them try to `include daal.lst` while it's not present in the repository and contributors should manually change the name of the file to include a list of examples. More than that, makefile itself is trying to refer to `makefile` and fails to do that. So contributors should manually rename makefile and list

**To Reproduce**
1. Setup
- source ICC
- source Java
- build DAAL
- source DAAL vars
2. Call
```
cd ./examples/cpp
mv daal_lnx.lst daal.lst
make -f makefile_lnx sointel64 example=kmeans_dense_batch mode=build threading=sequential
```
3. See error
```
make _make_ex _IA=intel64 RES_EXT=a
make[1]: Entering directory '/home/rpovelik/dev/daal/examples/cpp'
make[1]: *** No rule to make target '_make_ex'.  Stop.
make[1]: Leaving directory '/home/rpovelik/dev/daal/examples/cpp'
makefile_lnx:123: recipe for target 'libintel64' failed
make: *** [libintel64] Error 2
```

**Expected behavior**
Success

**Environment:**
 - OS: Ubuntu 18.04
 - Compiler: icpc 19u5
 - Version: 2f4ad00fdfadba45769faf46927f6bd165112224

**Proposal**
Divide infra in different folders like mac, lnx, windows

**Comment by SmirnovEgorRu** [comment]
Hi @PovelikinRostislav, DAAL examples are copied to release directory, it is right way to build them:
```sh
cd ./__release_lnx/daal/examples/cpp
make example=kmeans_dense_batch mode=build threading=sequential
```
instead of:
```sh
cd ./examples/cpp
mv daal_lnx.lst daal.lst
make -f makefile_lnx sointel64 example=kmeans_dense_batch mode=build threading=sequential
```

**Comment by PovelikinRostislav** [comment]
Hi @SmirnovEgorRu,
I've checked the cmd you sent me: it should work if you add a target `libia32|soia32|libintel64|sointel64`

Thanks for the help!
We can close an issue
