### ISSUE TITLE
Moving Doxygen-files in sub directory

### ISSUE THREAD

**Issue by SmirnovEgorRu** [intel/daal#180]
Here are too many files for Doxygen in the root directory, it is not frequently used functionality and it complicates access to other important files in root-folder like makefiles:
![image](https://user-images.githubusercontent.com/18555970/68074078-3eb6a100-fda8-11e9-8f9a-3eeaa2caa129.png)

My proposal is moving them in some sub-folder and check that all QA infrastructure works correctly.

**Comment by outoftardis** [comment]
These files seems to be used only for API generation for classical DAAL, which means that we might not want to have them in our **master** and **releases** branches at all. The same goes for the content of the `custom` folder.

Possible solution: 
* **master and releases branches:** remove these doxygen files and the `custom` folder completely
* **mnt branch:** move the doxygen files and the `custom` folder into a sub-foler

**Comment by outoftardis** [comment]
Decided on a different solution:
* `mnt` branch: do nothing
* for `master` and `releases` branches: move doxygen configs and `custom` folder into `docs/doxygen` folder

**Comment by napetrov** [comment]
Change have been implemented in both master and releases
