### ISSUE TITLE
Python Examples

### ISSUE THREAD

**Issue by whiletruelearn** [intel/daal#22]
As per the [documentation](https://software.intel.com/sites/default/files/managed/03/5c/daal_2017_u3_dev_guide.pdf) , Python examples should be present in `examples` directory.  I couldn't find them. Would be helpful if you could update this in documentation.

**Comment by dr-pain** [comment]
Hello!

DAAL has python interfaces (and examples for them), but in commercial version only.

Andrey

**Comment by kskrishnasangeeth** [comment]
what about the Pydaal [package](https://anaconda.org/intel/pydaal) in `conda` ?

The introductory video sort of mislead me to believe that this was opensource :disappointed:
