### ISSUE TITLE
helper scripts still need to be fixed

### ISSUE THREAD

**Issue by dr-pain** [intel/daal#246]
**Describe the bug**
when you try to download mklfpk at macOS in the same folder after build at linux, ./mklfpk.sh reported "Intel(R) MKL small libraries are already installed in /.../externals/mklfpk" and doesn`t download anything.

**Comment by KalyanovD** [comment]
There is a proposal how to avoid this situation
https://github.com/intel/daal/pull/452

**Comment by KalyanovD** [comment]
https://github.com/intel/daal/pull/452 was merged, this issue may be closed.
