### ISSUE TITLE
PCA DAAL 2017

### ISSUE THREAD

**Issue by vivien7806** [intel/daal#28]
Hi,

Since daal update 2017 PCA doesn't work if the number of rows is inferior than the number of columns using HomogenousNumericTable.

Thanks,

Vivien

**Comment by vepifanov** [comment]
Hi Vivien,

Intel DAAL version of PCA algorithm requires number of rows to be greater than the number of columns. We analyze the ways to support another case in the algorithm as well and will look on a way to support this in future versions of the library.

**Comment by vivien7806** [comment]
Hi,
Thanks for your answer,
I'm 100% sure It was working with the DAAL 2016 version.
