### ISSUE TITLE
Incorrect 'fullNUsers' parameter with implicit_als_csr_distributed_mpi.cpp

### ISSUE THREAD

**Issue by fleapapa** [intel/daal#32]
Hi, i'm experiencing an error with the sample code implicit_als_csr_distributed_mpi.cpp in which i changed the input CSR file sources as well as changed the constant 'nUsers' from 46 to 2145. 

The error shown with all 4 MPI processes are the same, as follows:

> daal::services::interface1::Exception'
>   what():  Incorrect parameter
> Details:
> Parameter name: **fullNUsers**
> 

For debugging purpose, i inserted code to log the shapes of the two sparse matrixes, **dataTable** and **transposedDataTable**. The printed log is as follow for the 4 processes:

> dataTable->getNumberOfRows=**534**
> dataTable->getNumberOfColumns=8656
> transposedDataTable->getNumberOfRows=2164
> transposedDataTable->getNumberOfColumns=2145
> 
> dataTable->getNumberOfRows=537
> dataTable->getNumberOfColumns=8656
> transposedDataTable->getNumberOfRows=2164
> transposedDataTable->getNumberOfColumns=2145
> 
> dataTable->getNumberOfRows=537
> dataTable->getNumberOfColumns=8656
> transposedDataTable->getNumberOfRows=2164
> transposedDataTable->getNumberOfColumns=**2144**
> 
> dataTable->getNumberOfRows=537
> dataTable->getNumberOfColumns=8656
> transposedDataTable->getNumberOfRows=2164
> transposedDataTable->getNumberOfColumns=2145
> 
> 

Though some of the row/column numbers above are not all equal to 537 or 2145, it should not be the problem, because i also log for original sample code and original CSR files, and found the numbers are  neither the same. 

I'm stuck, because i found nothing wrong with nUsers = 2145. 

Any idea what's wrong will be appreciated!!

**Comment by Vika-F** [comment]
@fleapapa, it looks like the issue happens because transposedDataTable has incorrect size in process # 3:
> transposedDataTable->getNumberOfColumns=2144

Should be:
transposedDataTable->getNumberOfColumns=2145

Please modify createSparseTable function in service.h. Let the function accept the number of columns of the CSR numeric table (nFeatures), and use the provided number to create the resulting table here:
`CSRNumericTable *numericTable = new CSRNumericTable(resultData, resultColIndices, resultRowOffsets, nFeatures, nVectors);`

Then you can create transposedDataTable with proper number of columns in each process.
Can you please try this and tell us about the results?

**Comment by fleapapa** [comment]
Yes, i will try that, but i'm very curious why DAAL original sample files can work while mine don't. Original sample files also have **unequal** getNumberOfColumns results, because their shapes are as follow:

    "./data/distributed/implicit_als_trans_csr_1.csv" ---> (5, 46)
    "./data/distributed/implicit_als_trans_csr_2.csv", ---> (5, 46)
    "./data/distributed/implicit_als_trans_csr_3.csv", --> (5, **45**)
    "./data/distributed/implicit_als_trans_csr_4.csv" --> (**6**, 46)

PS. I use scipy.csr_matrix to check their shapes:)

**Comment by fleapapa** [comment]
By the way, a quick (but very important for my sake:) question. Does DAAL ALS requires every row and every column of input sparse matrixes to have at least one non-zero value?

**Comment by fleapapa** [comment]
Update:

For the latest 'quick' question, i found the answer. It's 'No' :)

For the fullNUsers issue, i found the root cause is my mistake. I did not process the order of the file names correctly when i derive input CRS files and their transposed counterparts from a set of 4 CSV files which contains the source of 'implicit preferences'. (The implicit preference was learned via K-Mean.)

After i sorted the file names, the issue has gone. I'm closing this issue and very appreciating your comments and advices. Thanks a lot!!

**Comment by fleapapa** [comment]
I need to reopen this issue, because when i change my data dimension (nusers, nitems) from (5438, 9999) to (5438, 99999), the same exception pops up again.

The exception comes from this line of code in 

>     size_t nRows = algInput->get(data)->getNumberOfRows();
>     DAAL_CHECK_EX(algParameter->fullNUsers > nRows, ErrorIncorrectParameter, ParameterName, fullNUsersStr());
> 

Because the algorithm takes *transpose* matrix, in the case nBlocks = 4,  the variable nRows is 25000 (=(99999+4-1)/4) while algParameter->fullNUsers is 5438, so the check fails and aborts.

Does the condition in the check need to be corrected or the check need to be discarded?

**Comment by Vika-F** [comment]
@fleapapa Please give us couple of days to analyze this issue.
Can you please also provide the information about how the data is split across the nodes, i.e. the sizes of dataTable and transposedDataTable on each node?

**Comment by fleapapa** [comment]
Thanks for the reply.

Here you go.

>                    dataTable[0]= 1360, 99982
> transposedDataTable[0]= 25000, 5438
>                   dataTable[1]= 1360, 99997
> transposedDataTable[1]= 25000, 5438
>                    dataTable[2]= 1360, 99995
> transposedDataTable[2]= 25000, 5432
>                   dataTable[3]= 1358, 99998
> transposedDataTable[3]= 24998, 5438
>

**Comment by fleapapa** [comment]
Forgot to mention that now i have to add 1 to the actual number of users to make my code not exception-ed:)

`	
    nUsers = transposedDataTable->getNumberOfRows() + 1;
    initAlgorithm.parameter.fullNUsers = nUsers;
`

The + 1 seems an odd workaround...

**Comment by Vika-F** [comment]
It looks like you use older version of the sample with the newer version of the library.
There was an API change in implicit ALS algorithm in DAAL 2018 Beta Update 1.

I attach the sample that is compatible with DAAL 2018 Beta Update 1. Can you please try this sample and tell us about the results?

Thank you,
Vika
[implicit_als_csr_distributed_mpi.zip](https://github.com/01org/daal/files/1266945/implicit_als_csr_distributed_mpi.zip)
