### ISSUE TITLE
Minor issue: daal produces lots of warnings in pedantic modes

### ISSUE THREAD

**Issue by emmenlau** [intel/daal#353]
**Describe the bug**
This is not really a bug, rather a suggestion for an improvement. The issue is that when we include DAAL 2019.5 headers, we get a huge number of compiler warnings on all platforms.

This is due to our strict compiler settings, like `-Wall -Wextra -pedantic` on Linux and `/W4` on Windows. It seems DAAL can currently not be used nicely with such strict compiler settings, because we get thousands of lines of warnings. This makes our work a bit more complicated because our internal code review requests warning-free code.

Most warnings seem quite simple to fix. For example there are many cases of extra `;` that could be removed.

**To Reproduce**
1. Set Linux compiler warnings to `-pedantic -Wall -Wextra -Werror=return-type -Werror=uninitialized -Werror=unknown-pragmas` or Windows compiler warnings to `/W4`
2. Include standard daal headers
3. Build the code
4. There are typically 100-10000 lines of warnings per source file

**Expected behavior**
Ideally, DAAL would only show a few or now warnings at all.

**Output/Screenshots**
Here an example from Ubuntu 18.04 x86_64 with `gcc-7.4.0`:
```
 In file included from /data/Tools/include/algorithms/neural_networks/layers/dropout/dropout_layer_backward.h:30:0,
                  from /data/Tools/include/algorithms/neural_networks/layers/dropout/dropout_layer.h:31,
                  from /data/Tools/include/daal.h:256,
                  from /home/builds/include/Regression.hh:23,
                  from /home/builds/src/Regression.cc:20:
/data/Tools/include/algorithms/neural_networks/layers/dropout/dropout_layer_backward_types.h:116:38: warning: extra ';' [-Wpedantic]
      DECLARE_SERIALIZABLE_CAST(Result);
```

**Environment:**
 - OS: Ubuntu 18.04 x86_64, macOS 10.13 XCode 9.4, macOS 10.14 XCode 11.3, MS Visual Studio 2017, MS Visual Studio 2019
 - Version: 2019 Update 5

**Comment by SmirnovEgorRu** [comment]
@emmenlau, thank you for reporting the issue.
Usually we build our examples without "-Wpedantic" flag and don't observe what you reported. We are looking at the the problem and how it can be resolved.

@dr-pain is assigned for this work.

**Comment by emmenlau** [comment]
Thanks a lot @SmirnovEgorRu for the positive feedback! I hope the issue is not causing hazzle, and its not very urgent. But we're looking forward if something can be improved!

**Comment by dr-pain** [comment]
@emmenlau 
I have fixed all gcc warnings (or most of them). See https://github.com/intel/daal/pull/408.
Check it please.
Andrey

**Comment by emmenlau** [comment]
Awesome @dr-pain, thanks! I'm currently using the binaries from official Intel, so I'll have to wait a bit for the 2020 Update 1. But I will happily close the issue as fixed! Thanks!

**Comment by dr-pain** [comment]
Hello @emmenlau !
Sorry, but we don`t plan to commit fixes to 2020 product line - use 2021 (master, releases) instead.
Andrey

**Comment by emmenlau** [comment]
Ok I'll check them out! Will they be released as binary download for all platforms too (like the current Intel downloads from the official website), or are these source releases?

**Comment by dr-pain** [comment]
yes, we have binary releases for 2021.
You may download them from "releases" folder (but for linux and macos only).
2021 oneDAL is also available at official web site in oneAPI KIT package https://software.intel.com/en-us/oneapi .
Andrey

**Comment by emmenlau** [comment]
Thanks Andrey! I'm really sorry and I feel very stupid to ask this, but: could you point me to the binary download for 2021? I've considered
  * The branch "releases" from https://github.com/intel/daal/tree/releases
  * The "releases" page from https://github.com/intel/daal/releases
  * The Installation section from https://github.com/intel/daal#installation

But in all cases, I do not see anything to download for 2021, neither classic DAAL nor oneDAL. I did not consider oneAPI KIT package because we're not ready for this yet, but anything else. Am I doing something wrong?

**Comment by dr-pain** [comment]
I`m really sorry, but I missed fact that we are not published oneDAL binary releases at github.
The only way to get changes in binaries is - download oneAPI KIT and install oneDAL. It should be possible to install oneDAL only and skip all other tools.
Changes should be available in beta06 release. it is next release after upcoming beta05 release. current available release is beta04.
Andrey
