### ISSUE TITLE
R Api?

### ISSUE THREAD

**Issue by JesseLimtiaco** [intel/daal#39]
Are there any plans for the release of an R Api?

Thanks!

**Comment by fschlimb** [comment]
We are about to start a Technical Preview for a (higher level) R API.
If you are interested in trying it out, please let us know. We are looking for people to evaluate it; any feedback will be appreciated and help providing a useful API to R.

**Comment by JesseLimtiaco** [comment]
Yes, I would be interested in trying it out. 

Thanks!

**Comment by chrisvwn** [comment]
> 
> 
> We are about to start a Technical Preview for a (higher level) R API.
> If you are interested in trying it out, please let us know. We are looking for people to evaluate it; any feedback will be appreciated and help providing a useful API to R.

Apologies for posting on an old thread. Information is very scarce on DAAL for R. Is the Technical Preview of the R API still on? Has it already been released. I am interested in this.

**Comment by fschlimb** [comment]
I must tell you that this effort has been put on hold.
Even though it's not a real replacement, you might want to look at this thread: https://software.intel.com/en-us/forums/intel-data-analytics-acceleration-library/topic/557011

**Comment by chrisvwn** [comment]
Thanks @fschlimb! This is very helpful. If I might add one more question. We have been looking at using Intel DAAL on an Intel Xeon Phi KNC (3120A) but we cannot seem to get it to offload processing to the MIC. We are still not sure if KNC is supported by DAAL. Would you happen to know if it is? And if so which versions?

**Comment by dr-pain** [comment]
Hello chrisvwn!

Sorry, but DAAL support XeonPhi starting from 72xx model (KNL).

Andrey

**Comment by chrisvwn** [comment]
Hi @dr-pain . 

Thank you for the information! We have been dreading it but now that we know for sure we are looking at collecting ML algos implementing MKL that we can modify for use in our rcpp + xeon phi (KNC) project. Should you or anyone have any sort of information that could help with this uphill task, we would be grateful.

Cheers,
Chris
