### ISSUE TITLE
In Neural Network Example, parameter has no member named batchSize

### ISSUE THREAD

**Issue by JesseLimtiaco** [intel/daal#40]
I got this error when trying to compile the neural network dense batch example posted in:

https://github.com/01org/daal/blob/92f4dde5a1e2d7f132111588f4513cc7c4578052/examples/cpp/source/neural_networks/neural_net_dense_batch.cpp

error: 'struct daal::algorithms::optimization_solver::sgd::interface1::Parameter<(daal::algorithms::optimization_solver::sgd::Method)0u>' has no member named 'batchSize'

The error comes from trying to assign a batchSize parameter to the sgdAlgorithm pointer:

SharedPtr<optimization_solver::sgd::Batch<> > sgdAlgorithm(new optimization_solver::sgd::Batch<>());

  float learningRate = 0.001f;

  sgdAlgorithm->parameter.learningRateSequence = NumericTablePtr(new HomogenNumericTable<>(1, 1, NumericTable::doAllocate, learningRate));

  /* Set the batch size for the neural network training */
  sgdAlgorithm->parameter.batchSize = batchSize;

**Comment by Vika-F** [comment]
Hello @JesseLimtiaco ,
Can you share with us additional details about the issue?
Which version of the library do you use, on which OS do you run the example, which compiler do you use to build the library and example?

Best regards,
Victoriya

**Comment by JesseLimtiaco** [comment]
Thanks Victoriya,

  I am using the daal version I downloaded from the intel website, the installer file is marked as w_daal_2017.3.210.  I am on windows 10 Professional OS and am using gcc version 4.6.3 for compatibility with Rtools 3.3.  Would I need to switch my compiler MSVC?

Thanks!

**Comment by Vika-F** [comment]
> Would I need to switch my compiler MSVC?
Yes, we do not support GNU compiler on Windows. Please switch to Microsoft Visual Studio* 2013 or 2015.
Please also use the example that is consistent with Intel DAAL version 2017 Update 3 that you use.
Here is the example: https://github.com/01org/daal/blob/daal_2017_update3/examples/cpp/source/neural_networks/neural_net_dense_batch.cpp

Best regards,
Victoriya
