### ISSUE TITLE
confusing install

### ISSUE THREAD

**Issue by moskiteau** [intel/daal#44]
The installation of dall and pydall and dall-extension is ridiculously confusing. 
I've installed the version on this git, but it doesn't have a install.sh. Maybe it was pre-built, so I just setted the vars with the scripts. Didn't work. 
Had to get the community version, but surprise, it's written it doesn't support python (wtf)
Finally, got a student XE studio version bloated with useless stuff (fortran compiler wtf)
Install pydaal and daal-extension, yay, finally over. Error, cpp code doesn't match (wtf)
Still, doesn't work, had to manually export DAALROOT var , doesn't work (wtf)
Build the pydaal source from the XE code (why bother making a conda wtf)

Now it almost, but it shoots: 

> /opt/intel/compilers_and_libraries_2018.2.199/linux/daal/examples/python$ python source/neural_networks/stoch_pool2d_layer_dense_batch.py
> Forward two-dimensional stochastic pooling layer input (first 10 rows):
> 5.308     9.869     1.019     4.292     6.081     6.586     2.411     4.767     3.256     6.030     
> 7.279     0.391     9.619     3.435     4.769     4.873     0.119     5.117     0.419     0.475     
> 6.616     6.192     0.402     9.744     9.991     9.105     1.691     2.606     9.535     7.829     
> 4.792     2.491     2.939     8.086     3.774     9.997     0.222     8.995     5.753     6.091     
> 7.701     6.415     1.684     8.983     4.285     9.018     0.552     7.706     2.590     0.412     
> 6.992     1.064     9.321     0.430     2.168     1.736     0.919     6.981     0.712     3.414     
> 5.794     1.062     0.955     0.390     3.013     9.954     3.197     3.992     6.936     8.148     
> 2.487     6.973     4.047     5.656     5.082     5.534     7.821     2.763     0.454     6.554     
> 2.205     7.840     7.382     1.619     6.567     7.584     8.356     5.501     8.191     2.608     
> 9.949     8.942     8.106     4.864     5.853     1.659     6.343     8.190     3.110     7.485     
> 
> Traceback (most recent call last):
>   File "source/neural_networks/stoch_pool2d_layer_dense_batch.py", line 75, in <module>
>     forwardLayer = stochastic_pooling2d.forward.Batch(nDim)
> AttributeError: 'module' object has no attribute 'forward

**Comment by daaltces** [comment]
We apologize for the confusion and inconvenience.

If you intend to use only the Python API of Intel DAAL (PyDAAL), the link to the conda package is here: [http://anaconda.org/intel/pydaal](http://anaconda.org/intel/pydaal). However our preferred install method is through the conda package manager, as versioning is an issue, in particular for Intel MKL and TBB threading library. You can use either the full conda bundle or the mini-conda lightweight package manager. To install, use “conda install –c intel pydaal” to get the latest DAAL version from Anaconda cloud. 
Once PyDAAL is successfully installed, install daal-extensions as per the instructions here: https://github.com/intel/daal-extensions
**Note that the Python examples you are trying to run don’t require daal-extensions.**

If you’d like to use the entire python distribution from intel, here is the install guide: [https://software.intel.com/en-us/articles/using-intel-distribution-for-python-with-anaconda](https://software.intel.com/en-us/articles/using-intel-distribution-for-python-with-anaconda)

Also, we have resources to help you:
To get up and running with DAAL in <1 hour, see our Gentle Intro Series: [https://software.intel.com/en-us/articles/gentle-introduction-to-pydaal-vol-1-data-structures](https://software.intel.com/en-us/articles/gentle-introduction-to-pydaal-vol-1-data-structures)

**Comment by moskiteau** [comment]
thank you! :+1:
