### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by rayrapetyan** [intel/daal#45]
I'm trying to port daal into FreeBSD. The library itself compiles fine, but when I try to compile a sample, I'm getting a lot of unresolved references defined in "libdaal_mkl_*.a" libraries. Is it possible to obtain a source code of these libraries to compile them natively and finalize porting? Thanks.

**Comment by rayrapetyan** [comment]
So any chances to obtain missed sources?

**Comment by dr-pain** [comment]
Hello rayrapetyan!

Sorry for delayed answer.

libdaal_mkl_*.a are custom build of , mostly,  Intel® Math Kernel Library (Intel MKL). Because Intel MKL doesn`t have open source variant, we can`t provide their source code.
Within next few days we will explore possibilities to provide libdaal_mkl_*.a libs for FreeBSD*.

Could you provide FreeBSD* and compiler version which you use?

Andrey

**Comment by rayrapetyan** [comment]
FreeBSD 11.1 (amd64), clang 4.0.0. Thanks.

**Comment by rayrapetyan** [comment]
Hi @dr-pain , I've created a branch based on intel:daal_2018_update2: 
https://github.com/rayrapetyan/daal/tree/FreeBSD_support

Build instructions (tested on FreeBSD 11.1-RELEASE-p10, clang version 4.0.0):

1. Replace mkl libs in daal_last/externals/mklfpk/fbsd/lib with ones compiled natively in FreeBSD (daal lib compiles OK anyway, but final targets will fail to compile with unresolved dependencies, the reason why this issue was created).
2. pkg install tbb-2018.2 openjdk8
3. setenv CPATH /usr/local/openjdk8/include:/usr/local/openjdk8/include/freebsd
4. gmake daal PLAT=fbsd32e COMPILER=clang

Let me know if you have any questions\issues. Thanks!

**Comment by dr-pain** [comment]
Hello @rayrapetyan !

sorry for delayed answer again.
I have looked into your branch and want to say what you did good job! Thank you!

I have successfully built DAAL dynamic libs and run example with them without modifications of mklfpk linux libs (I have just copied src\externals\mklfpk\lnx to src\externals\mklfpk\fbsd).
I have used your branch, but did some changes:
1. makefile. change "-u" option to "-Wl$(comma)-u -Wl$(comma)" in lines 529, 531, 559, 561
2. examples\cpp\makefile_lnx should be used as template for examples\cpp\makefile_fbsd
After that, one problem remains only - mklfpk libs refers to stderr&stdout symbols. It may be solved by adding code:
FILE *stdout=__stdoutp;
FILE *stderr=__stderrp;
into final application (or somewhere in DAAL sources).

Will look on static libs building issue - I see that something wrong with creation of them (libraries size is too small).

Andrey

**Comment by rayrapetyan** [comment]
@dr-pain, thanks. Mine static is 20MB:

 ls -la __release_fbsd_clang/daal/lib/intel64_fre/libdaal_core.a
-rw-r--r--  1 robert  wheel  20413048 Jul  3 16:48 __release_fbsd_clang/daal/lib/intel64_fre/libdaal_core.a

What's the expected size?

**Comment by dr-pain** [comment]
@rayrapetyan , >850Mb for libdaal_core.a, >100Mb for libdaal_sequential.a and libdaal_thread.a.

**Comment by rayrapetyan** [comment]
@dr-pain, thanks, and what about  undefined references? Could you provide mkl sources or at least natively compiled binaries?

**Comment by dr-pain** [comment]
@rayrapetyan ,
I have used native linux libs with no modifications + little modifications in makefile are required. See my prev answer.
If it will not help, send me build logs please.

**Comment by dr-pain** [comment]
@rayrapetyan 
I expect that you have added
#undef stdout
#undef stderr

FILE *stdout=__stdoutp;
FILE *stderr=__stderrp;
into your main.cpp global section (outside main function body).

my command line is:
clang++ -Wall -w -I./source/utils -I/usr/include/c++/v1 -I/usr/local/include  -m32 -std=c++11 -stdlib=libc++ -nostdinc++ -L/usr/local/lib/gcc6 ./source/association_rules/assoc_rules_apriori_batch.cpp -o _results/clang_ia32_parallel_so/assoc_rules_apriori_batch.exe -Wl,--start-group "/localdisk/agilev/daal-2018-u2-os-rls/src/__release_fbsd/daal/lib/ia32_fre"/libdaal_core.so "/localdisk/agilev/daal-2018-u2-os-rls/src/__release_fbsd/daal/lib/ia32_fre"/libdaal_thread.so  -L"/localdisk/agilev/daal-2018-u2-os-rls/src/__release_fbsd/daal/../tbb/lib/ia32_fre/gcc4.4" -ltbb -ltbbmalloc -lc -Wl,--end-group

So, try to:
1) add _linker_ options --start-group/--end-group around linked libs
2) remove libdaal_mkl_thread.a from command line. It should be linked into libdaal_thread.so already
3) change compiler to clang

**Comment by rayrapetyan** [comment]
#undef stdout
#undef stderr
did the trick, thanks a lot! I'll try to figure out why static lib is so small, but your help would be highly appreciated!

**Comment by dr-pain** [comment]
@rayrapetyan 
in my case, without this "trick" compilation failed with "incompatible redefinition" message. So, you may want to check your build logs.
Can I ask you question? What is the purpose of your DAAL to FreeBSD porting works?

**Comment by rayrapetyan** [comment]
In my case just adding "undef" resolved all issues and app build and runs fine:

> /usr/local/bin/cmake --build /ara/devel/sandbox/daal_dt/cmake-build-debug --target daal_dt -- -j 2
> /usr/local/bin/cmake -H/ara/devel/sandbox/daal_dt -B/ara/devel/sandbox/daal_dt/cmake-build-debug --check-build-system CMakeFiles/Makefile.cmake 0
> /usr/local/bin/gmake -f CMakeFiles/Makefile2 daal_dt
> gmake[1]: Entering directory '/ara/devel/sandbox/daal_dt/cmake-build-debug'
> /usr/local/bin/cmake -H/ara/devel/sandbox/daal_dt -B/ara/devel/sandbox/daal_dt/cmake-build-debug --check-build-system CMakeFiles/Makefile.cmake 0
> /usr/local/bin/cmake -E cmake_progress_start /ara/devel/sandbox/daal_dt/cmake-build-debug/CMakeFiles 2
> /usr/local/bin/gmake -f CMakeFiles/Makefile2 CMakeFiles/daal_dt.dir/all
> gmake[2]: Entering directory '/ara/devel/sandbox/daal_dt/cmake-build-debug'
> /usr/local/bin/gmake -f CMakeFiles/daal_dt.dir/build.make CMakeFiles/daal_dt.dir/depend
> gmake[3]: Entering directory '/ara/devel/sandbox/daal_dt/cmake-build-debug'
> cd /ara/devel/sandbox/daal_dt/cmake-build-debug && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /ara/devel/sandbox/daal_dt /ara/devel/sandbox/daal_dt /ara/devel/sandbox/daal_dt/cmake-build-debug /ara/devel/sandbox/daal_dt/cmake-build-debug /ara/devel/sandbox/daal_dt/cmake-build-debug/CMakeFiles/daal_dt.dir/DependInfo.cmake --color=
> gmake[3]: Leaving directory '/ara/devel/sandbox/daal_dt/cmake-build-debug'
> /usr/local/bin/gmake -f CMakeFiles/daal_dt.dir/build.make CMakeFiles/daal_dt.dir/build
> gmake[3]: Entering directory '/ara/devel/sandbox/daal_dt/cmake-build-debug'
> [ 50%] Building CXX object CMakeFiles/daal_dt.dir/main.cpp.o
> /usr/bin/c++   -I/ara/devel/sandbox/daal/__release_fbsd_clang/daal/include -I/ara/devel/sandbox/daal/__release_fbsd_clang/daal/examples/cpp/source/utils  -pthread -g   -std=gnu++11 -o CMakeFiles/daal_dt.dir/main.cpp.o -c /ara/devel/sandbox/daal_dt/main.cpp
> [100%] Linking CXX executable daal_dt
> /usr/local/bin/cmake -E cmake_link_script CMakeFiles/daal_dt.dir/link.txt --verbose=1
> /usr/bin/c++   -pthread -g   CMakeFiles/daal_dt.dir/main.cpp.o  -o daal_dt  -L/ara/devel/sandbox/daal/__release_fbsd_clang/daal/lib/intel64_fre  -L/ara/devel/sandbox/daal/externals/mklfpk/fbsd/lib/intel64  -L/usr/local/lib -Wl,-rpath,/ara/devel/sandbox/daal/__release_fbsd_clang/daal/lib/intel64_fre:/ara/devel/sandbox/daal/externals/mklfpk/fbsd/lib/intel64:/usr/local/lib -ldaal_core -ldaal_thread -ltbb -ltbbmalloc /ara/devel/sandbox/daal/externals/mklfpk/fbsd/lib/intel64/libdaal_mkl_thread.a 
> gmake[3]: Leaving directory '/ara/devel/sandbox/daal_dt/cmake-build-debug'
> [100%] Built target daal_dt
> gmake[2]: Leaving directory '/ara/devel/sandbox/daal_dt/cmake-build-debug'
> /usr/local/bin/cmake -E cmake_progress_start /ara/devel/sandbox/daal_dt/cmake-build-debug/CMakeFiles 0
> gmake[1]: Leaving directory '/ara/devel/sandbox/daal_dt/cmake-build-debug'

Output:
/ara/devel/sandbox/daal_dt/cmake-build-debug/daal_dt
The first element of the Cholesky factor: 5.26354e-315
Process finished with exit code 0

The reason I'm trying to port DAAL is a lack of working "Decision Trees" classifier for one of the CPP projects I'm working on. I've tried mlpack (created a port - https://www.freshports.org/math/mlpack/), but it produces some weak predictions (comparing to scikit-learn) - https://github.com/mlpack/mlpack/issues/1399. Then I've tried shogun, surprisingly it was very buggy - https://github.com/shogun-toolbox/shogun/issues/4282, author has rewritten the whole thing after that. Tried few other less popular libs, there are issues everywhere. 
DAAL looks like a well tested stable product, so hopefully it will show same or better results in predictions (comparing to scikit-learn).
Of course, I'm also just a big fun of FreeBSD, using this OS everywhere and want to contribute back as much as I can. 
So these two reasons. Thanks.

**Comment by dr-pain** [comment]
@rayrapetyan 
I have found the root of problem - FreeBSD ar utility doesn`t recognize "@" option which allow to read command line args from file. I also can`t find analog of this option :-(
So, need to rework scheme of adding object files into archive.
The simplest way (change link.static.fbsd macro to unconditional usage of link.static.fbsd.script) also doesn`t work at FreeBSD because long command line.
I have tried to process __work_clang/fbsd32/kernel/libdaal_core_link.txt line by line, but it takes too much time (one ar call per one file for ~5200 files).
Will try to invent something more useful.

**Comment by rayrapetyan** [comment]
@dr-pain, I've tried to overcome that with ar's "MRI Librarian Commands" (addmod) with an unwrapped list of obj files from the txt file. It took more than an hour producing a huge HDD and CPU load (still goes). Do you think 1Gb static lib makes any sense? I'm pretty sure no one will use it anyway, it will just sit and waste huge amount of space. What if we just drop it from the output? Thanks.

**Comment by rayrapetyan** [comment]
@dr-pain, yeah, I've stepped into the same... Any workaround for "too long command-line"? I've tried to create a shell script dynamically and execute from there but it's too bulky..

**Comment by rayrapetyan** [comment]
@dr-pain, nevermind, /usr/local/bin/ar works fine with @ :). Preparing final changes to commit...

**Comment by rayrapetyan** [comment]
@dr-pain, so the only problem left, the combination with comma doesn't work:
> clang++ -m64 -shared -Wl,--start-group -z relro -z now -z noexecstack __work_clang/fbsd32e/thread_dll/threading_tbb.o __work_clang/fbsd32e/thread_dll/service_thread_pinner_tbb.o externals/mk
> lfpk/fbsd/lib/intel64/libdaal_mkl_thread.a externals/mklfpk/fbsd/lib/intel64/libdaal_vmlipp_core.a -fPIC -Wl,-u -Wl, fpk_blas_avx2_daxpy -Wl,-u -Wl, fpk_blas_avx2_dgemm -Wl,-u -Wl, fpk_blas_
> avx2_dgemv -Wl,-u -Wl, fpk_blas_avx2_dsymm -Wl,-u -Wl, fpk_blas_avx2_dsyr -Wl,-u -Wl, fpk_blas_avx2_dsyrk -Wl,-u -Wl,....
gives:
> clang++: error: no such file or directory: 'fpk_blas_avx2_daxpy'
> clang++: error: no such file or directory: 'fpk_blas_avx2_dgemm'
> clang++: error: no such file or directory: 'fpk_blas_avx2_dgemv'
> clang++: error: no such file or directory: 'fpk_blas_avx2_dsymm'
> clang++: error: no such file or directory: 'fpk_blas_avx2_dsyr'
> clang++: error: no such file or directory: 'fpk_blas_avx2_dsyrk'
> clang++: error: no such file or directory: 'fpk_blas_avx2_saxpy'
> clang++: error: no such file or directory: 'fpk_blas_avx2_sgemm'
> clang++: error: no such file or directory: 'fpk_blas_avx2_sgemv'
> clang++: error: no such file or directory: 'fpk_blas_avx2_ssymm'
> clang++: error: no such file or directory: 'fpk_blas_avx2_ssyr'
> ...

**Comment by dr-pain** [comment]
@rayrapetyan 
I have prepared workaround tor BSD ar from /usr/bin :-) but your solution with /usr/local/bin/ar looks better. Lets leave it.
Hmm. "-Wl,-u -Wl, fpk_blas_avx2_dgemm" solution works fine for me. Which clang++ did you use? maybe FreeBSD has several versions of it as with ar.
I also plat to incorporate stdout/stderr definition into library to avoid necessity of this code in final application.

And main part.
Thank you for your involvement into FreeBSD support addition to DAAL! We will discuss how we will keep it.

Andrey

**Comment by rayrapetyan** [comment]
I've recently upgraded to 11.2 which uses clang version 6.0.0, maybe that's the reason.
I've also added stdout\stderr into daal sources and fixed double definition of sched_getaffinity (used extern in one of the sources instead). May I ask you - what's the purpose of -u funcname? Is it to avoid specifying daal_mkl_* libs when compiling user apps ot something else? Thanks!

**Comment by dr-pain** [comment]
I don`t try to make secret here :-)

man clang++:
-Wl,<args>
    Pass the comma separated arguments in args to the linker.

man ld:
-u symbol
--undefined=symbol
    Force symbol to be entered in the output file as an undefined
    symbol.  Doing this may, for example, trigger linking of additional
    modules from standard libraries.  -u may be repeated with different
    option arguments to enter additional undefined symbols.  This
    option is equivalent to the "EXTERN" linker script command.

libdaal_core.so needs fpk_* symbols from libdaal_sequential.so or libdaal_thread.so. To make these symbols visible, I need to specify them via -u linket option. Otherwise, linker will made them internal.

nm libdaal_thread.so | grep fpk_ (library built with -u):
...
01265ff0 T fpk_blas_ssse3_dcopy
012661f0 T fpk_blas_ssse3_ddot
...
nm libdaal_thread.so | grep fpk_ (library built without -u) gives nothing.

Will ask our IT dept to install new FreeBSD 11.2 and do experiments.

**Comment by dr-pain** [comment]
@rayrapetyan 
I tested at FreeBSD 11.2 server too:
[agilev@nnviclef134 ~]$ uname -a
FreeBSD nnviclef134 11.2-RELEASE FreeBSD 11.2-RELEASE #0 r335510: Fri Jun 22 04:32:14 UTC 2018     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
[agilev@nnviclef134 ~]$ clang++ --version
FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
Target: x86_64-unknown-freebsd11.2
Thread model: posix
InstalledDir: /usr/bin

build should work.
Could you put your latest changes to branch?

**Comment by rayrapetyan** [comment]
Done, please check. I'm getting all these errors at the very end of process.

**Comment by dr-pain** [comment]
Hello @rayrapetyan !
I have tried to build DAAL from your branch. And now I see where problem is. 
makefile , strs 529, 531, 559, 561: remove extra space from the middle of "-Wl$(comma) ,$(shell".
I also have couple of changes in makefile which help to avoid presence of /externals/mklfpk/fbsd
folder (which is duplication of /externals/mklfpk/lnx). Will put my makefile here later today.

**Comment by rayrapetyan** [comment]
Thanks, committed all suggested changes. Now everything works fine! Let me know if I need to perform a pull request into your branch...

**Comment by dr-pain** [comment]
Hello  @rayrapetyan !

We have added FreeBSD support to DAAL some time ago - it should be DAAL 2019 Update 1. Could you try it?
I`m terrible sorry for late notification.

Andrey

**Comment by rayrapetyan** [comment]
With a few minor changes I was able to compile DAAL libs and examples on FreeBSD (see PR #53). Thanks.
