### ISSUE TITLE
neural network training batch problem causing issue in pydaal wrapper

### ISSUE THREAD

**Issue by AnnaZuzex** [intel/daal#46]
The interface of the function initialize here unlike in most of the code takes directly Topology class object instead of the pointer to this object. 
https://github.com/intel/daal/blob/daal_2019_beta/include/algorithms/neural_networks/neural_networks_training.h#L150

In the python wrapper it is only possible to work with classes as pointers. When constructor is used shared ptr to the object topology is returned and it is not possible to dereference this pointer in the python code.

So the usage of this function is not possible and there is no other public function in the class which will allow to set a topology for the network.

Possible solution could be override the function to support pointers instead of objects as input.

**Comment by RuslanIsrafilov** [comment]
@AnnaZuzex, thank you for pointing that out, we will analyse how it can be resolved in future releases.
