### ISSUE TITLE
Missing Logistic Regression in 2019 Beta

### ISSUE THREAD

**Issue by sbodenstein** [intel/daal#48]
In the 'DAAL Developer Guide 2019 Beta', logistic regression is documented and the example code `./examples/cpp/source/logistic_regression/log_reg_dense_batch.cpp` is referenced. But I cannot find this anywhere in either `daal_2019_beta` or `daal_2019_beta_experimental` branches.

**Comment by daaltces** [comment]
I am sorry for the confusion here. Logistic regression is not in Intel DAAL 2019 Beta, it will be in Intel DAAL 2019 Gold. If you need further information about logistic regression, we may communicate through emails. Thank you!

**Comment by sbodenstein** [comment]
Thank you for the clarification!
