### ISSUE TITLE
Wrong RowMatrix dimension [Spark SampleSVD]

### ISSUE THREAD

**Issue by dennlinger** [intel/daal#49]
In the `SampleSVD.scala` file, the RowMatrix passed to the `computeSVD()` function is defined with explicit dimensions calculated from these two lines:
```
val nRows = data.count()
val nCols = data.first.length
```
When looking at data, we notice that this is still the raw input text file, ergo the values have neither been converted to double, nor split at the blanks (this happens only in dataRDD).

Therefore, the returned value of nCols is actually 168 (number of characters in the first line of the text file), instead of the desired 18 "value dimensions".
Surprisingly, Spark does not seem to care too much, since the computations are performed fine. From what I got out of the results, this seems to simply pad the vector with zeros.

Simply replacing the nCols calculation with
`val nCols = dataRDD.first.size`
will correctly register the number of columns.

**Comment by dennlinger** [comment]
I also noticed that - even with corrected input matrix dimensions - the resulting matrix has an extremly weird shape.

Although the results should be (from my understanding of the little documentation that is out there) a full SVD, i.e. either a matrix of size
 - 4000x4000
 - 18x18
 I am getting a resulting matrix that has 4000x18, yet the underlying dataRDD only shows entries of size 36x18, which is extremly strange. I investigated whether this is simply a concatenation of the 18x18 matrix in dimension 0, but that is not the case; all of the eigenvalues are distinct.

If anyone can shed a little light on this behavior, it would be greatly appreciated. Since Spark is essentially calling the Java backend, I might try to investigate what the results are for that example.

**Comment by vepifanov** [comment]
Hi dennlinger,

Thanks for you reply!

val nCols = data.first.length
is definitely a typo, your changes are correct.

According to the documentation it should return a matrix of size 4000x18 in your case.
We will also look into this sample to provide more detailed answer.

Meanwhile, you can try a slightly updated version of the SVD sample which is closer to MLLib interfaces.
You can refer to MLLib documentation as well - https://spark.apache.org/docs/2.2.0/mllib-dimensionality-reduction.html

[sample_svd.zip](https://github.com/intel/daal/files/2170387/sample_svd.zip)

**Comment by dennlinger** [comment]
So I just ran the new example you gave me, and made the following observations:
I seem to be able to use matrices with an arbitrary dimension, which was something I could not do previously (see my thread in the [Intel Forums](https://software.intel.com/en-us/forums/intel-data-analytics-acceleration-library/topic/781724)).

Yet, the results still confuse me, since the resulting matrices have the following properties:
 - U is of dimension 4000x18 according to the properties of `numRows` and `numCols`, but the underlying RDD still has only 36x18 non-zero entries. 
 - s is a vector of size 18 (correct), but only contains zeros.
 - V is of size 18x18, but also only contains zeros.

Aside from this, IMO an SVD should return U in the dimension of MxM, i.e. in this case 4000x4000.
The 4000x18 matrix is, if I remember that correctly, only to describe the eigenvalues, which are contained in s anyways.

**Comment by rlnx** [comment]
Answered at Intel Forum
https://software.intel.com/en-us/forums/intel-data-analytics-acceleration-library/topic/781724
