### ISSUE TITLE
Memory leak in service_topo.cpp on Windows x64 with core count more 32

### ISSUE THREAD

**Issue by VasilyevAlexander** [intel/daal#50]
1. On Windows x64 system in service_topo.h type LNX_PTR2INT is defined as follows:
        #ifdef  _x86_64
            #define LNX_PTR2INT __int64
            #define LNX_MY1CON 1LL
        #else
            #define LNX_PTR2INT unsigned int
            #define LNX_MY1CON 1
        #endif
Under Windows x64 **macro _M_X64 should be used**.
Because LNX_PTR2INT is defined as **unsigned int** which on Windows is **32 bit**
then function static int __internal_daal_countBits(DWORD_PTR x) return **maximum of 32**,
then functiion static void  __internal_daal_setChkProcessAffinityConsistency( unsigned int lcl_OSProcessorCount )
in statement on line 328 
       if( sum != lcl_OSProcessorCount ) // check cumulative bit counts matches processor count 
**determines inconsistensy**;
then in function static int __internal_daal_queryParseSubIDs(void) in statement on line 1346
      if( glbl_obj.error )
           return -1;
error is detected which is returned to function static void __internal_daal_buildSystemTopologyTables()
which leads to exit without initialization
2. In function static void __internal_daal_buildSystemTopologyTables()
tables are allocated on line 1683 and **should be deallocated** in case of an error 
before returns on lines: 1687, 1689, 1694
function __internal_daal_buildSystemTopologyTables is called from 
__internal_daal_buildSystemTopologyTables which is called from
__internal_daal_initCpuTopology which is called from
__internal_daal_GetSysProcessorCoreCount which is called from
GetL1CacheSize which is called in evere call to **compute**

**Comment by dr-pain** [comment]
Hello Alexander!
1. now we are thinking about disabling TheradPinning functionality at Windows. Do you use TheradPinning?
We will fix it, if it will be decided to keep TheradPinning.
2. glktsn has destructor (glktsn::FreeArrays() in the same source). all allocated tables free in it.
Andrey

**Comment by dr-pain** [comment]
Hello!
Ok. Now I understand the usage case and see where problem is.
If you use open source DAAL, as quick workaround, I suggest to build libs with define DAAL_CPU_TOPO_DISABLED.
Andrey

**Comment by VasilyevAlexander** [comment]
Hello, Andrey

Yes, there are two problems:

1. Using macro _x86_64 instead of _M_X64 in service_topo.h (at least on with Windows with MSVC compiler)

2. Incorrect clean up after error.

I have corrected issue #1 and everithing is working (at least for less than 64 cores)

Thanks,

Alexander
