### ISSUE TITLE
make daal PLAT=lnx32e COMPILER=gnu failed

### ISSUE THREAD

**Issue by WeiChungChang** [intel/daal#51]
### **[Error]**
`========= Building core =========
ar rs __work_gnu/lnx32e/kernel/libdaal_core_link.a @__work_gnu/lnx32e/kernel/libdaal_core_link.txt && printf '\n%s\n' '__work_gnu/lnx32e/kernel/libdaal_core_link.a.mkdeps += makefile build/cmplr.gnu.mk build/common.mk build/deps.mk makefile.ver' '$(__work_gnu/lnx32e/kernel/libdaal_core_link.a.mkdeps):' '__work_gnu/lnx32e/kernel/libdaal_core_link.a: $(__work_gnu/lnx32e/kernel/libdaal_core_link.a.mkdeps)' '__work_gnu/lnx32e/kernel/libdaal_core_link.a.trigger = ar rs __work_gnu/lnx32e/kernel/libdaal_core_link.a @__work_gnu/lnx32e/kernel/libdaal_core_link.txt' >> __work_gnu/lnx32e/kernel/libdaal_core_link.a.d.tmp && mv -f __work_gnu/lnx32e/kernel/libdaal_core_link.a.d.tmp __work_gnu/lnx32e/kernel/libdaal_core_link.a.d
ar: creating __work_gnu/lnx32e/kernel/libdaal_core_link.a
printf "create __work_gnu/lnx32e/daal/lib/libdaal_core.a\naddlib externals/mklfpk/lnx/lib/intel64/libdaal_vmlipp_core.a\n addlib __work_gnu/lnx32e/kernel/libdaal_core_link.a\n\n\n\nsave\n" | ar -M && printf '\n%s\n' '__work_gnu/lnx32e/daal/lib/libdaal_core.a.mkdeps += makefile build/cmplr.gnu.mk build/common.mk build/deps.mk makefile.ver' '$(__work_gnu/lnx32e/daal/lib/libdaal_core.a.mkdeps):' '__work_gnu/lnx32e/daal/lib/libdaal_core.a: $(__work_gnu/lnx32e/daal/lib/libdaal_core.a.mkdeps)' '__work_gnu/lnx32e/daal/lib/libdaal_core.a.trigger = printf "create __work_gnu/lnx32e/daal/lib/libdaal_core.a\naddlib externals/mklfpk/lnx/lib/intel64/libdaal_vmlipp_core.a\n addlib __work_gnu/lnx32e/kernel/libdaal_core_link.a\n\n\n\nsave\n" | ar -M' >> __work_gnu/lnx32e/daal/lib/libdaal_core.a.d.tmp && mv -f __work_gnu/lnx32e/daal/lib/libdaal_core.a.d.tmp __work_gnu/lnx32e/daal/lib/libdaal_core.a.d
ar: externals/mklfpk/lnx/lib/intel64/libdaal_vmlipp_core.a: File format not recognized
makefile:368: recipe for target '__work_gnu/lnx32e/daal/lib/libdaal_core.a' failed
make: *** [__work_gnu/lnx32e/daal/lib/libdaal_core.a] Error 1
`
### [Env]:
cc (Ubuntu 6.4.0-17ubuntu1~16.04) 6.4.0 20180424
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

### [command to make]
make daal PLAT=lnx32e COMPILER=gnu

**Comment by WeiChungChang** [comment]
Dear  SmirnovEgorRu 

Thanks for your kindly suggestion, you are right.

Although I wonder why git clone makes such corrupt file, after getting this file by directly downloading from github, it is O.K

Thanks again here.

**Comment by SmirnovEgorRu** [comment]
Glad to hear it!
Can you, please, close the issue in this case?

**Comment by ArniDagur** [comment]
I'm trying to make an Arch Linux package for this project, and this is the error I'm getting:
```
g++ -D__int64="long long" -D__int32="int" -m64 -Wformat -Wformat-security -O2 -D_FORTIFY_SOURCE=2 -fstack-protector -fPIC -std=c++11   -DDAAL_HIDE_DEPRECATED -D__DO_TBB_LAYER__ @./__work_gnu/lnx32e/thread_dll/thr_inc_y_folders.txt -D__DAAL_IMPLEMENTATION   -c  -o__work_gnu/lnx32e/thread_dll/service_thread_pinner_tbb.o algorithms/threading/service_thread_pinner.cpp && printf '\n%s\n' '__work_gnu/lnx32e/thread_dll/service_thread_pinner_tbb.o.mkdeps += makefile build/cmplr.gnu.mk build/common.mk build/deps.mk makefile.ver' '$(__work_gnu/lnx32e/thread_dll/service_thread_pinner_tbb.o.mkdeps):' '__work_gnu/lnx32e/thread_dll/service_thread_pinner_tbb.o: $(__work_gnu/lnx32e/thread_dll/service_thread_pinner_tbb.o.mkdeps)' '__work_gnu/lnx32e/thread_dll/service_thread_pinner_tbb.o.trigger = g++ -D__int64="long long" -D__int32="int" -m64 -Wformat -Wformat-security -O2 -D_FORTIFY_SOURCE=2 -fstack-protector -fPIC -std=c++11   -DDAAL_HIDE_DEPRECATED -D__DO_TBB_LAYER__ @./__work_gnu/lnx32e/thread_dll/thr_inc_y_folders.txt -D__DAAL_IMPLEMENTATION   -c  -o__work_gnu/lnx32e/thread_dll/service_thread_pinner_tbb.o algorithms/threading/service_thread_pinner.cpp' >> __work_gnu/lnx32e/thread_dll/service_thread_pinner_tbb.o.d.tmp && mv -f __work_gnu/lnx32e/thread_dll/service_thread_pinner_tbb.o.d.tmp __work_gnu/lnx32e/thread_dll/service_thread_pinner_tbb.o.d
printf "create __work_gnu/lnx32e/daal/lib/libdaal_sequential.a\naddlib externals/mklfpk/lnx/lib/intel64/libdaal_mkl_sequential.a\n\naddmod __work_gnu/lnx32e/thread/threading_seq.o __work_gnu/lnx32e/thread/service_thread_pinner_seq.o\n\nsave\n" | ar -M && printf '\n%s\n' '__work_gnu/lnx32e/daal/lib/libdaal_sequential.a.mkdeps += makefile build/cmplr.gnu.mk build/common.mk build/deps.mk makefile.ver' '$(__work_gnu/lnx32e/daal/lib/libdaal_sequential.a.mkdeps):' '__work_gnu/lnx32e/daal/lib/libdaal_sequential.a: $(__work_gnu/lnx32e/daal/lib/libdaal_sequential.a.mkdeps)' '__work_gnu/lnx32e/daal/lib/libdaal_sequential.a.trigger = printf "create __work_gnu/lnx32e/daal/lib/libdaal_sequential.a\naddlib externals/mklfpk/lnx/lib/intel64/libdaal_mkl_sequential.a\n\naddmod __work_gnu/lnx32e/thread/threading_seq.o __work_gnu/lnx32e/thread/service_thread_pinner_seq.o\n\nsave\n" | ar -M' >> __work_gnu/lnx32e/daal/lib/libdaal_sequential.a.d.tmp && mv -f __work_gnu/lnx32e/daal/lib/libdaal_sequential.a.d.tmp __work_gnu/lnx32e/daal/lib/libdaal_sequential.a.d
ar: externals/mklfpk/lnx/lib/intel64/libdaal_mkl_sequential.a: file format not recognized
make: *** [makefile:510: __work_gnu/lnx32e/daal/lib/libdaal_sequential.a] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...
```
With this package build (package function is incomplete):
```shell
pkgname='intel-daal'
packager='Árni Dagur'
pkgver=2019.1.1
_tagname=${pkgver/./_u}
pkgrel=1
arch=('x86_64')
url='https://software.intel.com/en-us/intel-daal'
license=('Apache-2.0')
makedepends=('git-lfs')

# source=("$pkgname-$pkgver.tar.gz::https://github.com/intel/daal/archive/$_tagname.tar.gz")
# sha256sums=('7aaa8d184391548f529d989ac180da34e90368efd7fb002972550f589da50502')

prepare() {
    cd "$srcdir"
    if [[ -d "daal" ]]; then
        cd "daal" && git pull origin
    else
        git clone --recursive https://github.com/intel/daal.git
    fi
}

build() {
    # cd daal-$_tagname
    cd daal
    # I'm not sure which of these I need to source
    source bin/daalvars_lnx.sh intel64
    source /opt/intel/pkg_bin/compilervars.sh intel64
    make daal PLAT=lnx32e COMPILER=gnu
}

package() {
    # cd daal-$_tagname
    cd daal
    install -d "$pkgdir/usr/lib"
}
```
As you can see, I tried both `git clone` and `curl`-ing the source directly from the releases section. Both result in the same problem.

**Comment by dr-pain** [comment]
Hello!
What is the externals/mklfpk/lnx/lib/intel64/libdaal_mkl_sequential.a size?
Looks like Git LFS at your workstation works wrong or not installed.
Andrey
