### ISSUE TITLE
Is there any difference between this version of DAAL and the one included with Parallel Studio XE (prebuilt binary)?

### ISSUE THREAD

**Issue by ArniDagur** [intel/daal#54]

**Comment by dr-pain** [comment]
Hello!

no functional differences between DAAL at github and in Parallel Studio XE except two things:
1) DAAL at github doesn`t contain python interfaces (pydaal)
2) DAAL at github doesn`t have pre-built binaries for Windows

And we are trying to do releases at github more often. For example, latest DAAL version at github is 2019u1.1. latest available DAAL in Parallel Studio XE is 2019u1.

Andrey

**Comment by ArniDagur** [comment]
Thank you for the clear and concise answer.
