### ISSUE TITLE
 [CRASH] - gradient boosted trees from java

### ISSUE THREAD

**Issue by cnuernber** [intel/daal#55]
When gridsearching gradient boosted trees I am getting a crash from deep in GBT

[hs_err_pid8204.log](https://github.com/intel/daal/files/2923457/hs_err_pid8204.log)
 

This doesn't happen if I just use the default parameters.  The gridsearch space is defined here:

https://github.com/techascent/tech.lentils/blob/master/src/tech/libs/daal/regression/gradient_boosted_trees.clj#L33

**Comment by SmirnovEgorRu** [comment]
Hi @cnuernber ,
What version of Intel DAAL do you use?

Gradient Boosting requires some additional memory allocation for training. If you have many instances of gbt.regression.training.TrainingBatch class **_in the same time_** - memory usage can be large enough, as result it leads to errors related to out of memory.
How many instances of TrainingBatch do you have at the same time? Do you do gridsearching in parallel or sequential? Try to reduce this number of instances if it possible.

Please let us know if it answers your question. Also, feel free to ask, if you have more questions about algorithms from Intel DAAL.

**Comment by SmirnovEgorRu** [comment]
@cnuernber, we added checks for memory allocations in this PR (https://github.com/intel/daal/pull/85), so no crashes are expected now.

If you still have any issues with DAAL's algorithms usage - let us know.
