### ISSUE TITLE
makefile is not compatible for cross compilation. 

### ISSUE THREAD

**Issue by apnavik** [intel/daal#57]
When I tried to compile for yocto framework, it fails due to cross compilation issue. 
It throws an error for static library "File format not recognized".

**Comment by dr-pain** [comment]
Hello!
not so much info for 100% diagnose.
But try to install GitLFS.
Andrey

**Comment by apnavik** [comment]
Hello, 
Sorry my bad. 
Let me clear the doubt. I cant use git lfs in Yocto. 
Hence I am using tar.gz version of DAAL and I want to use daal component in Yocto framework for IoT edge device. 
When I tried to compile, I get following error. 

ar: externals/mklfpk/lnx/lib/intel64/libdaal_mkl_sequential.a: File format not recognized
makefile:475: recipe for target '__work_gnu/lnx32e/daal/lib/libdaal_sequential.a' failed
make: *** [__work_gnu/lnx32e/daal/lib/libdaal_sequential.a] Error 1             
make: *** Waiting for unfinished jobs....                                       
make: *** wait: No child processes.  Stop.                                      
ERROR: oe_runmake failed

**Comment by dr-pain** [comment]
Hello!
Am I understand correctly that you are trying to build daal for different than Intel architecture?
Andrey

**Comment by apnavik** [comment]
Hi @dr-pain 
I am building for Intel Architecture only. I am just using Yocto framwork (meta-intel). 
http://git.yoctoproject.org/cgit/cgit.cgi/meta-intel 

Yocto provides custom linux for embedded system.

**Comment by dr-pain** [comment]
Hello!
so, our and your target architectures should be the same.
Looks like the problem in libdaal_sequential.a file. What is the size of it?
GitHUB doesn`t have support of GitLFS too and if you download (not clone) repo as tar.gz you will not receive proper files from GitLFS.
Andrey

**Comment by rlnx** [comment]
> GitHUB doesn`t have support of GitLFS too and if you download (not clone) repo as tar.gz you will not receive proper files from GitLFS.

@dr-pain, looks like this is a problem. If user downloads the source code as an archive from the releases tab, they cannot build DAAL since `libdaal_mkl_sequential.a` is not available. Is there other way (not LFS) to obtain micro mkl libs?

**Comment by dr-pain** [comment]
Hello Ruslan!
1. it isn`t MKL libs only. They contain other fuctionality also.
2. "libdaal_mkl_sequential.a is not available" it is available, but content is wrong.
3. "Is there other way (not LFS) to obtain micro mkl libs" it is possible to donwload code from other OS which "support" GitLFS. 
3.1 DAAL isn`t published elsewhere that Intel site and github. But we can upload needed DAAL OS parts to asked places. For example, to @apnavik ftp server.
Andrey

**Comment by apnavik** [comment]
@dr-pain
Could you please upload to your ftp server. ?
Let me know if anything required from my side.

**Comment by dr-pain** [comment]
@apnavik 
is it OK for you if I put DAAL sources to my personal Google Drive?
Andrey

**Comment by apnavik** [comment]
@dr-pain 
If it doesn't have any license obligation then it should be fine. 
I am just wondering why tar.gz or .zip version doesn't download proper files. 

Regards, Ankit

**Comment by dr-pain** [comment]
@apnavik
I have uploaded DAAL 2019 update 3 sources to https://drive.google.com/file/d/1NTGqftd37ucfJgDTUc6AwbODuVwiB56T/view?usp=sharing
Note: mac and windows libs were deleted to reduce size. let me know if you need these binaries.
Andrey

**Comment by apnavik** [comment]
I still see, the makefiles are hard coded with g++, ar instead of ${CXX} and ${AR}.
At few place such as ./build/common.mk is trying to invoke host ar

Could you please look into this and use implicit variables as per GNU?

**Comment by napetrov** [comment]
@kiselik @dr-pain  - guess this issue can be closed as corresponding PR have been merged already?

**Comment by apnavik** [comment]
Yes its merged. closing the issue. Thanks
