### ISSUE TITLE
Single cpu build doesn't work

### ISSUE THREAD

**Issue by napetrov** [intel/daal#96]
**Describe the bug**
Library build fails in case of using REQCPU="avx2" option for build. 

**To Reproduce**
1. Checkout sources
2. Call make with make daal -j4 PLAT=lnx32e COMPILER=gnu REQCPU="avx2"
3. Build fails 

**Expected behavior**
Library should be successfully build with optimization for selected and base CPUs

**Output/Screenshots**
Public CI run - https://github.com/intel/daal/runs/219127300 

```
In file included from ./algorithms/kernel/adaboost/adaboost_predict_kernel.h:29:0,
                 from ./algorithms/kernel/adaboost/adaboost_predict_batch_container.h:29,
                 from ./algorithms/kernel/adaboost/adaboost_predict_dense_default_batch_fpt_dispatcher.cpp:26:
./algorithms/kernel/kernel.h:58:83: error: expected identifier before ‘;’ token
 extern template class DAAL_KERNEL_SSSE3_CONTAINER1(ContainerTemplate, __VA_ARGS__);              \
```

**Environment:**
 - OS: Any
 - Compiler: Any
 - Version: DAAL 2020

**Comment by dr-pain** [comment]
Hello @napetrov !
We have some period of time when "one cpu" build was broken. But it should be fixed by first commit of @orazve . Could you verify it?
Andrey
